title: "William Chuang"
description: "Graduate Student at the University of Arizona"
author:
  name: "William Chuang"
  email: "williamchuang@arizona.edu"
  
# Where your site is hosted (change if not user.github.io):
url: "https://williamchuang.github.io"
baseurl: ""

# Build settings
markdown: kramdown
theme: null

# Plugins (optional, remove if not needed or if not supported by GitHub Pages)
# If you are using GitHub Pages, these are typically allowed:
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalink structure (optional)
permalink: /:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Additional configuration for Kramdown (optional)
kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: "lsquo, rsquo, ldquo, rdquo"
  entity_output: as_char
  toc_levels: 1..6

# Additional site config as needed...

